### ISSUE TITLE
[req] Consider moving the orientation out of the constructor

### ISSUE THREAD

**Issue by ADraginda** [AharonSambol/PrettyPrintTree#2]
Moved this converstaion out of Reddit 👋 

I love the new changes and have a suggestion:

instead of 

```python
pt = PrettyPrintTree(lambda x: x.children, lambda x: x.val, orientation=PrettyPrintTree.HORIZONTAL)
...
pt(tree)
```

Consider instead

```python
pt = PrettyPrintTree(lambda x: x.children, lambda x: x.val,
...
pt(tree, orientation=PrettyPrintTree.HORIZONTAL)
```

My argument: the constructor doesn't need to know about the orientation, only the renderer needs that option

**Comment by AharonSambol** [comment]
Hi! Thanks for the feedback
I was kind of thinking that putting it in the constructor makes it easier to print and less repetitive (since you only need to make the constructor once and then can print multiple times)
But I hear your argument too 🤔 Maybe I can have it optional to put in either one and the one in the call overrides the one in the constructor (if any were set there)?
Just like I did with max_depth
wdyt?

**Comment by ADraginda** [comment]
I see your point, yeah both seem like a good idea: Perhaps in the constructor, it's instead labeled "default_orientation"? I'm being a bit pedantic but the orientation is not something that the constructor actually needs to know about. My rationale here is that if you had the object...

```python
pt = PrettyPrintTree(..., orientation=PrettyPrintTree.HORIZONTAL)
```

You can get the attribute `orientation` from the object but what would that even mean without the render. Thus, if it were instead labeled as the _default_ orientation, the meaning and context would be clear?

**Comment by AharonSambol** [comment]
Sure that seems like a good idea

**Comment by AharonSambol** [comment]
Any reason this is specific to orientation and not all the settings?

**Comment by AharonSambol** [comment]
Hi! Thanks for the feedback
I was kind of thinking that putting it in the constructor makes it easier
to print and less repetitive (since you only need to make the
constructor once and then can print multiple times)
But I hear your argument too 🤔 Maybe I can have it optional to put in
either one and the one in the call overrides the one in the constructor (if
any were set there)?
Just like I did with max_depth
wdyt?

**Comment by AharonSambol** [comment]
In the new version all the settings can be given a default in the ctor and overriden when called
